
### BEGIN yaml FOR BOOK'S WEBSITE (Aug 12, 2023) ###
project:
  type: website
  output-dir: docs

website:
  title: "Data Analytics 101 -- Exploratory Data Analysis using R"

  margin-header: |
    ![](BookCover101.png)  
  page-footer:
    background: "blue"
    center: 
      - text: "Sameer Mathur"
        href: https://www.qatar.cmu.edu/directory/sameer-mathur/
      - text: "Aryeman Gupta Mathur"
        href: https://docs.google.com/document/d/15Li_DpXPSA6NXyXyCzM3vUu766RBq87W/edit?usp=sharing&ouid=100224206438187222136&rtpof=true&sd=true
  navbar:
    background: "blue"
    pinned: false
    search: false
    right: 
      - icon: globe
        href: https://www.qatar.cmu.edu/directory/sameer-mathur/
        text: "Sameer Mathur"
        target: "_blank"  
#      - icon: globe
#        href: https://docs.google.com/document/d/15Li_DpXPSA6NXyXyCzM3vUu766RBq87W/edit?usp=sharing&ouid=100224206438187222136&rtpof=true&sd=true
#        text: "Aryeman Gupta Mathur"
#        target: "_blank"
      - icon: github
        href: https://github.com/SameerMathur/DataAnalytics101
        text: "Book's Github"
        target: "_blank"

  sidebar:
    logo: "images/openscapes_hex.png"
    background: "#FEC20C"
    pinned: true
    align: center
    style: "docked"
    search: true
    collapse-level: 1
    footer: ""
    contents:
      - href: index.qmd
        text: Overview
      - 01GettingStarted.qmd
      - 02RPackages.qmd
      - 03DataStructures.qmd
      - 04ReadingData.qmd
      - 05ExploringDataframes.qmd
      - 06ExploringTibbles.qmd
      - 07CategoricalData01.qmd
      - 08CategoricalData02.qmd
      - 09CategoricalData03.qmd
      - 10ContinuousData01.qmd
      - 11ContinuousData02.qmd
      - 12ContinuousData03.qmd
      - 13ContinuousData04.qmd
      - 14ContinuousData05.qmd
      - 15ContinuousData06.qmd
      - 16ThreeDimensions01.qmd
#      - 16LiveCase01.qmd
#      - 17LiveCase02.qmd
#      - 18LiveCase03.qmd

### END yaml FOR BOOK'S WEBSITE ###

format:
  html:
    theme: united
    toc: true # may need to comment this out to revert this back to the book
    fig-width: 8
    fig-height: 4
    code-fold: false
    prefer-html: true
  pdf:
    documentclass: scrreport
    header-includes: |
      \titlehead{
        \begin{center}
          \includegraphics[width=5in]{FINALIZED BOOK COVER.png}
        \end{center}
      }
    prefer-html: true

editor: visual

